name: Build and run tests on Windows
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
env:
  VCPKG_DEFAULT_BINARY_CACHE: "${{github.workspace}}/vcpkg-cache"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Cache vcpkg packages
        uses: actions/cache@v4
        with:
          path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
          key: ${{ runner.os }}-vcpkg-cache-1
          restore-keys: |
            ${{ runner.os }}-vcpkg-binary-cache-1

      - name: Install dependencies
        run: |-
          md -Force $env:VCPKG_DEFAULT_BINARY_CACHE
          vcpkg install --triplet x64-windows `
            boost-algorithm boost-endian boost-format boost-functional boost-program-options `
            glm sdl2 glew openal-soft libmad ffmpeg wxwidgets gtest

      - name: Generate solution
        run: |-
          mkdir build
          cmake -S . -B build `
            -G "Visual Studio 17 2022" -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake

      - name: Build solution
        working-directory: ${{github.workspace}}/build
        run: cmake --build . --config Release

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest -VV -C Release
